import type { BenchmarkDatasetCatalogEntry } from './benchmarkTypes';

const createJsonlTemplate = (prefix: string, language: string, domain: string, tags: string[]) =>
  JSON.stringify({
    id: `${prefix}-001`,
    fileName: `${prefix}/sample-001.wav`,
    referenceText: 'Replace with the official reference transcript.',
    language,
    domain,
    duration: 0,
    speaker: 'unknown',
    noise: tags.includes('noisy') ? 'noisy' : 'clean',
    tags,
    keywords: [],
    names: [],
    terms: [],
  });

export const benchmarkDatasetCatalog: BenchmarkDatasetCatalogEntry[] = [
  {
    id: 'librispeech',
    name: 'LibriSpeech',
    languages: ['en'],
    scenario: '英文朗读语音',
    recommendedSubset: 'test-clean / test-other',
    manifestTemplate: createJsonlTemplate('librispeech-test-clean', 'en', 'read', ['clean', 'read', 'short']),
    downloadUrl: 'https://www.openslr.org/12/',
    license: 'CC BY 4.0',
    notes: '适合做英文基础准确率、clean/noisy 差异和通用 WER baseline。',
    tags: ['english', 'read', 'clean', 'classic'],
  },
  {
    id: 'aishell-1',
    name: 'AISHELL-1',
    languages: ['zh'],
    scenario: '普通话朗读语音',
    recommendedSubset: 'test',
    manifestTemplate: createJsonlTemplate('aishell-1-test', 'zh', 'read', ['mandarin', 'read', 'clean']),
    downloadUrl: 'https://www.openslr.org/33/',
    license: 'Apache 2.0 style research license',
    notes: '适合中文 CER/WER、普通话基础识别和数字/人名回归。',
    tags: ['chinese', 'mandarin', 'read'],
  },
  {
    id: 'fleurs',
    name: 'FLEURS',
    languages: ['zh', 'en', 'ja', 'ko'],
    scenario: '多语言短语音',
    recommendedSubset: 'zh_cn / en_us / ja_jp / ko_kr test',
    manifestTemplate: createJsonlTemplate('fleurs-zh-cn-test', 'zh', 'multilingual', ['fleurs', 'multilingual']),
    downloadUrl: 'https://huggingface.co/datasets/google/fleurs',
    license: 'CC BY 4.0',
    notes: '适合跨语言对比、低资源语言 smoke test 和统一题型 benchmark。',
    tags: ['multilingual', 'short', 'benchmark'],
  },
  {
    id: 'common-voice',
    name: 'Mozilla Common Voice',
    languages: ['multi'],
    scenario: '社区真实口音语音',
    recommendedSubset: 'validated subset by language',
    manifestTemplate: createJsonlTemplate('common-voice-validated', 'en', 'crowd', ['accent', 'crowd', 'validated']),
    downloadUrl: 'https://commonvoice.mozilla.org/en/datasets',
    license: 'CC0 / dataset-specific metadata terms',
    notes: '适合口音、设备差异和真实用户语音鲁棒性评测。',
    tags: ['accent', 'crowd', 'multilingual'],
  },
  {
    id: 'earnings22',
    name: 'Earnings-22',
    languages: ['en'],
    scenario: '财报电话会长音频',
    recommendedSubset: 'small balanced subset',
    manifestTemplate: createJsonlTemplate('earnings22', 'en', 'earnings-call', ['long', 'business', 'meeting']),
    downloadUrl: 'https://github.com/revdotcom/speech-datasets/tree/main/earnings22',
    license: 'Dataset license in Rev speech-datasets repository',
    notes: '适合长音频、多人、金融术语、数字和真实电话会议评估。',
    tags: ['long', 'business', 'finance'],
  },
  {
    id: 'ami',
    name: 'AMI Meeting Corpus',
    languages: ['en'],
    scenario: '会议多说话人',
    recommendedSubset: 'scenario meetings test split',
    manifestTemplate: createJsonlTemplate('ami-meeting', 'en', 'meeting', ['meeting', 'multi-speaker']),
    downloadUrl: 'https://groups.inf.ed.ac.uk/ami/corpus/',
    license: 'Research license',
    notes: '适合说话人分离、会议转写、speaker turn 和时间戳评测。',
    tags: ['meeting', 'speaker', 'diarization'],
  },
  {
    id: 'chime',
    name: 'CHiME',
    languages: ['en'],
    scenario: '噪声/远场/多麦克风',
    recommendedSubset: 'CHiME-6 / CHiME-7 eval subset',
    manifestTemplate: createJsonlTemplate('chime-noisy', 'en', 'noisy-meeting', ['noisy', 'far-field', 'meeting']),
    downloadUrl: 'https://www.chimechallenge.org/datasets',
    license: 'Challenge dataset terms',
    notes: '适合噪声、远场、会议和复杂声学环境压力测试。',
    tags: ['noisy', 'far-field', 'meeting'],
  },
];

export const getBenchmarkDatasetCatalogEntry = (id: string) => {
  return benchmarkDatasetCatalog.find((entry) => entry.id === id) ?? benchmarkDatasetCatalog[0];
};
